// examples/react-example/src/App.tsx
import { useEffect, useState } from "react";
import reactLogo from "./assets/react.svg";
import clerkLogo from "./assets/clerk-dark.svg";
import { invoke } from "@tauri-apps/api/core";
import "./App.css";

import type { Clerk } from "@clerk/clerk-js";
import { init } from "tauri-plugin-clerk";

const AppLoaded = () => {
  const [greetMsg, setGreetMsg] = useState("");
  const [name, setName] = useState("");

  async function greet() {
    // Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
    setGreetMsg(await invoke("greet", { name }));
  }
  return (
    <>
      <div className="row">
        <a href="https://vitejs.dev" rel="noreferrer" target="_blank">
          <img src="/vite.svg" className="logo vite" alt="Vite logo" />
        </a>
        <a href="https://tauri.app" rel="noreferrer" target="_blank">
          <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
        </a>
        <a href="https://reactjs.org" rel="noreferrer" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
        <a href="https://clerk.com/" rel="noreferrer" target="_blank">
          <img src={clerkLogo} className="logo Clerk" alt="React logo" />
        </a>
      </div>
      <p>Click on the Tauri, Vite, React, and Clerk logos to learn more.</p>

      <form
        className="row"
        onSubmit={(e) => {
          e.preventDefault();
          greet();
        }}
      >
        <input
          id="greet-input"
          onChange={(e) => setName(e.currentTarget.value)}
          placeholder="Enter a name..."
        />
        <button type="submit">Greet</button>
      </form>
      <p>{greetMsg}</p>
    </>
  );
};

const LoadingClerk = () => {
  return <div>Loading clerk...</div>;
};

const App = () => {
  const [clerk, setClerk] = useState<Clerk | null>(null);

  useEffect(() => {
    // avoid double loading in dev
    const timeout = setTimeout(() => init({}).then(setClerk), 16);
    return () => clearTimeout(timeout);
  }, []);

  return (
    <main className="container">
      <h1>Welcome to Tauri + React + Clerk</h1>
      {clerk ? <AppLoaded /> : <LoadingClerk />}
    </main>
  );
};

export default App;

// examples/tauri-app/src/App.svelte
<script>
  import Greet from './lib/Greet.svelte'
  import { ping } from 'tauri-plugin-clerk-api'

	let response = ''

	function updateResponse(returnValue) {
		response += `[${new Date().toLocaleTimeString()}] ` + (typeof returnValue === 'string' ? returnValue : JSON.stringify(returnValue)) + '<br>'
	}

	function _ping() {
		ping("Pong!").then(updateResponse).catch(updateResponse)
	}
</script>

<main class="container">
  <h1>Welcome to Tauri!</h1>

  <div class="row">
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo vite" alt="Vite Logo" />
    </a>
    <a href="https://tauri.app" target="_blank">
      <img src="/tauri.svg" class="logo tauri" alt="Tauri Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank">
      <img src="/svelte.svg" class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>

  <p>
    Click on the Tauri, Vite, and Svelte logos to learn more.
  </p>

  <div class="row">
    <Greet />
  </div>

  <div>
    <button on:click="{_ping}">Ping</button>
    <div>{@html response}</div>
  </div>

</main>

<style>
  .logo.vite:hover {
    filter: drop-shadow(0 0 2em #747bff);
  }

  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00);
  }
</style>
